# Generated by Django 5.1.5 on 2025-03-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogs_rename_descriptions_contact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('usn', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('college_name', models.CharField(max_length=100)),
                ('offer_status', models.CharField(max_length=60)),
                ('start_date', models.CharField(max_length=60)),
                ('end_date', models.CharField(max_length=60)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
